### ISSUE TITLE
Can i use this app without Heroku ?

### ISSUE THREAD

**Issue by designskiller** [jeKnowledge/slack-birthday-bot#4]

**Comment by jbernardo95** [comment]
@designskiller You can, if you setup your system's cron to do so.

Heroku scheduler works like the cron. So just setup a cron to run the rake task.

This might help: http://tutorials.jumpstartlab.com/topics/systems/automation.html

We will add a guide on how to setup cron for this project in the near future :)

**Comment by designskiller** [comment]
@jbernardo95 Thank you!

**Comment by jbernardo95** [comment]
@designskiller Just updated the `README` with setup instructions for a custom server 😉
